# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - runs Parcel to bundle the project
  command = "yarn build"
  
  # Publish directory - where Parcel outputs the bundled files
  publish = "dist"
  
  # Node.js version to use
  [build.environment]
    NODE_VERSION = "22.20.0"

# Redirect rules for SPA behavior (optional, for clean URLs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/solve.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/code.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
